### PR TITLE
discard decrpecated GLOBAL, package.json cleanup

### PR DESCRIPTION
**Pull request by zhuangya**

### CODE REVIEW

**Comment by ottomao** [comment]
What's the purpose of replacing GLOBAL by global ?

**Comment by zhuangya** [comment]
it's deprecated.

**Comment by zhuangya** [comment]
```
$ anyproxy -i
the default rule for AnyProxy which supports CORS.
Anyproxy rules initialize finished, have fun!
(node:35393) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
GUI interface started at : http://10.2.212.215:8002/
Http proxy started at 10.2.212.215:8001

```

**Comment by jeremyrajan** [comment]
+1! it would be ideal, if that deprecation warning is fixed please.

**Comment by zhuangya** [comment]
@ottomao any idea about this?

**Comment by codingfishman** [comment]
@zhuangya 
  Sorry that the code base changed and there are conflicts now. We'll to this to the code, thanks for you contribution!

  BTW, it would be appreciated if you will accept [CLA](https://cla-assistant.io/alibaba/anyproxy?pullRequest=69)  when you make the PR:)

**Pull request closed without merging**
